---

- name: Provision guides
  vars:
    app_root: /var/www/alchemy-guides/html
    home: /var/www/alchemy-guides
    app_user: guides
    hostname: guides.alchemy-cms.com
  hosts: production
  remote_user: root
  roles:
    - nginx-static
    - static-site
